accounts/urls.py
from django.urls import path

from . import views

app_name = "autorization"
urlpatterns = [
    path("singup/", views.SignUpView.as_view(), name="signup"),
]

chat/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chat_groups.urls')),
    path('', views.home, name='home'),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
]

chat_groups/urls.py
from django.urls import path
from . import views

app_name = "groups"
urlpatterns = [
   path('group/', views.defining_groups, name='group'),
   path('group/create', views.create_group, name='create'),
   path('group/enter', views.enter_group, name='enter'),

   path('group/groupname/<str:group_name>', views.entred_group, name='group_entered'),
]

accounts/models.py
from django.db import models

# Create your models here.

chat_groups/models.py
from django.db import models


# Create your models here.
class Group(models.Model):
    name = models.CharField(max_length=50)
    password = models.CharField(max_length=100, default='')

    def __str__(self):
        return self.name


class Mensage(models.Model):
    group = models.ForeignKey(Group, on_delete=models.CASCADE)
    user = models.CharField(max_length=50)
    content = models.TextField()
    date = models.DateTimeField("date published")

    def __str__(self):
        return self.content

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView


class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/singup.html"

chat/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')

chat_groups/views.py
from django.shortcuts import render, redirect
from .models import Group, Mensage
from django.utils import timezone


def defining_groups(request):
    # defines the errors
    enter_error = request.session.get('enter_error', '')
    request.session['enter_error'] = ''
    creation_error = request.session.get('creation_error', '')
    request.session['creation_error'] = ''

    user = request.user

    if not user.is_authenticated:
        return redirect('login')

    # show the page if there's a user, if there isn't the user goes to the login page
    return render(request, 'groups/group_define.html', {'creation_error': creation_error, 'enter_error': enter_error})


def create_group(request):
    # gets the group name and password
    group_name = request.POST.get('group_name', '')
    password = request.POST.get('password', '')

    # gives an error if the group already exists
    if Group.objects.filter(name=group_name).exists():
        request.session['creation_error'] = "This group already exists"
        return redirect("groups:group")

    # creates a group if group_name isn't null
    if group_name:
        g = Group.objects.create()
        g.name = group_name
        g.password = password
        g.save()
    else:
        request.session['creation_error'] = "You did't fill one of the fields"
        return redirect("groups:group")

    return redirect("groups:group_entered", group_name=group_name)


def enter_group(request):
    # gets the group name and password
    group_name = request.POST.get('group_name', '')
    password = request.POST.get('password', '')

    # verify if the group exist and the password is correct
    if Group.objects.filter(name=group_name).exists():
        if Group.objects.get(name=group_name).password == password:
            return redirect("groups:group_entered", group_name=group_name)
        else:
            request.session['enter_error'] = "Wrong password"
            return redirect("groups:group")

    request.session['enter_error'] = "Group doesn't exist"
    return redirect("groups:group")


def entred_group(request, group_name):
    user = request.user
    password = request.session.get('password', '')
    if (Group.objects.get(name=group_name).password != password) or (not user.is_authenticated):
        return redirect("groups:group")

    request.session['group_name'] = group_name
    request.session['password'] = password
    messages = list(Mensage.objects.filter(group=Group.objects.get(name=group_name)))
    messages.reverse()
    return render(request, 'groups/group.html', {'group_name': group_name, 'user': user, 'messages': messages, 'is_banned': user.groups.filter(name="Banned").exists()})

chat_groups/templates/groups/group.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}
    {{ group_name }}
{% endblock %}

{% block statics %}
    <style>
        #messages {
            height: 67vh;
            border: 2px solid rgb(255, 255, 255);
            border-radius: 10px;
            overflow: scroll;
            order: revert;
            background-color: rgb(107, 107, 107);
        }

        #write_and_send {
            border-top: 1px solid white;
            background-color: rgb(49, 49, 49);

            width: 100%;

            position:fixed;
            bottom: 0;
            left: 50%;
            transform: translate(-50%, 0%);

            padding-top: 5px;
        }

        header {
            text-align: start;
        }

        #block {
            color: red;
        };
    </style>
{% endblock %}

{% block content %}
    <header>
        <a id="sing" href="{% url 'groups:group' %}">&lt;--</a>
    </header>
    <div id="title">
        <h1>Welcome <span id="user-name">{{ user }}</span> to <span id="group-name">{{ group_name }}</span></h1>
    </div>
    <div id="messages">
        {% for message in messages %}
            <div>
                <strong>{{ message.user }}</strong> send on {{ message.date|date:"M-d-Y H:i" }}:<br>
                {{ message.content }}
            </div>
            <hr>
        {% endfor %}
    </div>
    <div id="write_and_send">
        <label for="message">Message</label>
        <input id="message" type="text" name="message" placeholder="Write your message">
        <button id="get-message" type="submit">Send</button>
        <span id="block"></span>
    </div>

    {{ is_banned|json_script:"is-banned" }}
    <script>
        const user_name = document.querySelector('#user-name').innerHTML;
        const group_name = document.querySelector('#group-name').innerHTML;
        const roomName = group_name;
        const is_banned = JSON.parse(document.getElementById('is-banned').textContent);

        var chatSocket

        console.log(window.location.href)
        console.log(window.location.href[4])
        if (window.location.href[4] === 's') {
            chatSocket = new WebSocket(
                `wss://${window.location.host}/ws/chat/${roomName}/`
            );
        }
        else {
            chatSocket = new WebSocket(
                `ws://${window.location.host}/ws/chat/${roomName}/`
            );
        };


        chatSocket.onmessage = (e) => {
            const data = JSON.parse(e.data);
            if (data.message.is_blocked) {
                document.getElementById('block').innerHTML = 'You are blocked';
                is_banned = true
            }
            else {
                let message_conteiner = document.querySelector('#messages');
                message_conteiner.innerHTML = `<div><strong>${data.message.user}</strong> send on ${data.message.date}:<br>${data.message.message}</div><hr>${message_conteiner.innerHTML}`
            };
        };

        chatSocket.onclose = (e) => {
            console.error('Chat socket closed unexpectedly');
        };

        document.querySelector('#message').focus();
        document.querySelector('#message').onkeyup = (e) => {
            if (e.key === 'Enter') {  // enter, return
                document.querySelector('#get-message').click();
            }
        };

        document.querySelector('#get-message').onclick = (e) => {
            if (!is_banned) {
                const messageInputDom = document.querySelector('#message');
                const message = messageInputDom.value;
                if (message) {
                    chatSocket.send(JSON.stringify({
                        'message': message,
                        'user': user_name,
                        'group': group_name
                    }));
                    messageInputDom.value = '';
                }
                else {
                    throw "You can't send a null message!";
                }
            }
            else {
                document.getElementById('block').innerHTML = 'You are blocked'
            }
        };
    </script>
{% endblock %}

chat_groups/templates/groups/group_define.html
{% extends 'layout.html' %}
{% load static %}

{% block title %}
    Groups
{% endblock %}

{% block statics %}
    <style>
        body {
            font-size: 20px;
        }

        #title {
            margin-top: 70px;
            font-size: 20px;
        }

        #logout {
            border: 0;
            background-color: transparent;
            text-decoration: underline;
            color: white;
        }

        #logout:hover {
            color:rgb(100, 100, 100);
        };
    </style>
{% endblock %}

{% block content %}
    <header>
        <form action="{% url 'logout' %}" method="post">
            {% csrf_token %}
            <button id="logout" type="submit">Log Out</button>
        </form>
    </header>
    <div id="title">
        <h1>Welcome {{ user.username }}</h1>
    </div>
    <h2>Create group</h2>

    {% if creation_error %}
        <p style="color: red;">{{ creation_error }}</p>
    {% endif %}

    <form action="{% url 'groups:create' %}" method="post">
        {% csrf_token %}
        <label for="group_name">Name</label>
        <input type="text" placeholder="Group name" name="group_name" required><br>
        
        <label for="password">Password</label>
        <input type="text" placeholder="Group password" name="password"><br>

        <button type="submit">Create</button>
    </form>

    <h2>Enter in a group</h2>

    {% if enter_error %}
        <p style="color: red;">{{ enter_error }}</p>
    {% endif %}

    <form action="{% url 'groups:enter' %}" method="post">
        {% csrf_token %}
        <label for="group_name">Name</label>
        <input type="text" placeholder="Group name" name="group_name" required><br>

        <label for="password">Password</label>
        <input type="text" placeholder="Group password" name="password"><br>

        <button type="submit">Enter</button>
    </form>
{% endblock %}

templates/home.html
{% extends 'layout.html' %}

{% block title %}
    Home
{% endblock %}

{% block statics %}
    <style>
        #singup {
            margin: 2vw;
        }

        #login {
            margin-right: 10px;
        }

        #title {
            text-align: center;
        }

        #conteiner {
            position: absolute;
            left: 50%;
            transform: translate(-50%, 0%); 
        }

        #content {
            border: .5vw solid white;
            border-radius: 10px;
            height: 60vh;
            margin: auto -7vw;
        }

        .information {
            margin-left: 2vw;
            margin-right: 1vw;
        };
    </style>

    <script>
        function tell_accounts() {
            alert("I don't have any social media");
        };
    </script>
{% endblock %}

{% block content %}
    <header>
        <a class="links" id="singup" href="{% url 'autorization:signup' %}">Singup</a>
        <a class="links" id="login" href="{% url 'login' %}">Login</a>
    </header>

    <div id="title">
        <h1>My chat web</h1>
    </div>

    <div id="conteiner">
        <div id="content">
            <p class="information">Hi, this is the home page of a personal project</p>
            <p class="information">Take a look on my <a href="" onclick="tell_accounts()">social medias</a></p>
        </div>
    </div>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock %}</title>

        <link href='https://fonts.googleapis.com/css?family=Comfortaa' rel='stylesheet'>
        <style>
            body {
                background-color: black;
                color: white;
                font-family: 'Comfortaa';
                font-size: 30px;
            }

            .links {
                font-size: 30px;
            }

            header {
                text-align: end;
                border-bottom: 1px solid white;
                display: block;
                width: 100%;
                position: fixed;
                top: 0;
                right: 0;
                background-color: rgb(19, 19, 19);
            }

            #title {
                font-size: 30px;
                margin-top: 20px;
            }

            a {
                color: white;
                text-decoration: underline;
            }

            a:hover {
                color:rgb(100, 100, 100)
            }

            button:hover {
                cursor: pointer;
            }

            input {
                border: 2px solid rgb(70, 70, 70);
                border-radius: 20px;

                background-color: white;
                margin-bottom: 10px;

                width: 250px;
                height: 30px;

                font-size: 20px;
            }

            button {
                border: 2px solid rgb(70, 70, 70);
                border-radius: 10px;

                background-color: white;

                width: 118px;
                height: 30px;

                font-size: 20px;
                font-weight: 500;
            }

            button:hover {
                border: 3px solid rgb(255, 255, 255);
                background-color: rgb(184, 184, 184);
            };
        </style>

        {% block statics %}{% endblock %}
    </head>
    <body>
        {% block content %}{% endblock %}
    </body>
</html>